# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VOISTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EduSigmaApp
   pod 'SVProgressHUD'
    pod 'Alamofire'
    pod 'IQKeyboardManagerSwift'
    pod 'SDWebImage'
    pod 'RxSwift'
    pod "RxGesture"
    pod 'RxCocoa'
    pod 'ReachabilitySwift'
end
